### ISSUE TITLE
Booting on mdv

### ISSUE THREAD

**Issue by Neelix57** [SinclairQL/uqlx-fork#8]
Hi,

I downloaded Psion programs from [here](http://www.dilwyn.me.uk/), and extracted the files from the archive in the mdv1 directory.

I'm unable to boot from mdv.

I compiled UQLX on Xubuntu Bionic 64bit. Tried with these [binaries](http://www.dilwyn.me.uk/emu/uqlx2017.zip) too, but unsuccessful.

Could you help, please ?

**Comment by xXorAa** [comment]
This is not a user support system, please ask on qlforum.co.uk
